%global module aiohttp
%bcond_without tests

Name:		python-aiohttp
Version:	3.13.2
Release:	1
Summary:	Python HTTP client/server for asyncio
License:	Apache-2.0
URL:		https://github.com/aio-libs/aiohttp
Group:		Development/Python
Source0:	https://files.pythonhosted.org/packages/source/a/aiohttp/aiohttp-%{version}.tar.gz

BuildRequires:	python
BuildRequires:	pkgconfig
BuildRequires:	pkgconfig(python)
BuildRequires:	python%{pyver}dist(cython)
BuildRequires:	python%{pyver}dist(pip)
BuildRequires:	python%{pyver}dist(pkgconfig)
BuildRequires:	python%{pyver}dist(setuptools)
BuildRequires:	python%{pyver}dist(wheel)

BuildRequires:	python%{pyver}dist(aiosignal)
BuildRequires:	python%{pyver}dist(aiohappyeyeballs)
BuildRequires:	python%{pyver}dist(attrs)
BuildRequires:	python%{pyver}dist(charset-normalizer)
BuildRequires:	python%{pyver}dist(frozenlist)
BuildRequires:	python%{pyver}dist(multidict)
BuildRequires:	python%{pyver}dist(uvloop)
BuildRequires:	python%{pyver}dist(yarl)
BuildRequires:	llhttp-devel >= 9.3.0

%if %{with tests}
BuildRequires:	python%{pyver}dist(brotli)
#BuildRequires:	python%%{pyver}dist(blockbuster)
BuildRequires:	python%{pyver}dist(freezegun)
#BuildRequires:	python%%{pyver}dist(gunicorn)
BuildRequires:	python%{pyver}dist(pluggy)
BuildRequires:	python%{pyver}dist(propcache)
BuildRequires:	python%{pyver}dist(pytest)
BuildRequires:	python%{pyver}dist(pytest-mock)
#BuildRequires:	python%%{pyver}dist(pytest-timeout)
#BuildRequires:	python%%{pyver}dist(pytest-xdist)
BuildRequires:	python%{pyver}dist(time-machine)
BuildRequires:	python%{pyver}dist(trustme)
%endif

%description
Python HTTP client/server for asyncio which supports both the client and the
server side of the HTTP protocol, client and server websocket, and webservers
with middlewares and pluggable routing.

%prep
%autosetup -p1 -n %{module}-%{version}

# Remove bundled llhttp
rm -rv vendor/llhttp
# Disable coverage test reports
sed -i '/--cov/d' setup.cfg
sed -r -i '/--cov=|-p pytest_cov/d' setup.cfg
sed -i '/--numprocesses=auto/d' setup.cfg

# Disable gunicorn
sed -r -i 's/^gunicorn/# &/' requirements/base.in

sed -r -i \
   -e 's/^(blockbuster|proxy[-\.]py|python-on-whales|wait-for-it)/# &/' \
%if 0%{?__isa_bits} == 32
   -e 's/^(isal)/# &/' \
%endif
   -e 's/^(coverage|pytest-cov|pytest_codspeed|mypy|re-assert|re_assert)/# &/' \
   -e 's/^(setuptools-git)/# &/' \
   requirements/test-common.in

# Make sure the source archive does not include any files generated by Cython
grep -rl '/\* Generated by Cython' | xargs -r rm -v

# don't treat DeprecationWarnings as errors in subprocess based tests
sed -i 's/"-W", "error"/"-W", "error", "-W", "ignore::DeprecationWarning"/' \
    tests/test_circular_imports.py

%build
export AIOHTTP_USE_SYSTEM_DEPS=1
export CFLAGS="%{optflags}"
%{__python} tools/gen.py
# Recreate removed Cython files using commands extracted from the Makefile.
# We don't run make directly, as it pip-installs Cython.
#
# See the aiohttp/_find_header.c target in the Makefile; this also generates
# _headers.pyi.
%{__python} -m cython -3 \
    aiohttp/*.pyx \
    aiohttp/_websocket/*.pyx \
    aiohttp/_websocket/reader_c.py \
    -I aiohttp
%py_build

%install
%py_install

%check
%if %{with tests}
export CI=true
export PYTHONPATH="%{buildroot}%{python_sitearch}:${PWD}"
export PYTHONSAFEPATH=1
# We do not want to run benchmarks (and we patched out their dependencies)
ignore="${ignore-} --ignore-glob=tests/test_benchmarks_*"
# test_proxy_functional.py requires python3dist(proxy-py)
ignore="${ignore-} --ignore=tests/test_proxy_functional.py"
# These require python-on-whales and a running Docker
ignore="${ignore-} --ignore=tests/autobahn"
# we dont carry python-re-assert, skip tests
ignore="${ignore-} --ignore=tests/test_streams.py"
ignore="${ignore-} --ignore=tests/test_urldispatch.py"
ignore="${ignore-} --ignore=tests/test_web_response.py"
ignore="${ignore-} --ignore=tests/test_client_session.py"
# These require network access (at least DNS):
k="${k-}${k+ and }not test_client_session_timeout_zero"
k="${k-}${k+ and }not test_invalid_idna"
k="${k-}${k+ and }not test_tcp_connector_ssl_shutdown_timeout_passed_to_create_connection[pyloop]"
k="${k-}${k+ and }not test_tcp_connector_ssl_shutdown_timeout_zero_not_passed[pyloop]"
k="${k-}${k+ and }not test_tcp_connector_ssl_shutdown_timeout_nonzero_passed[pyloop]"

# A slow builder may easily violate an arbitrary bound on how long it should
# take to import the package. This is not something we need to care about
# downstream.
k="${k-}${k+ and }not test_import_time"
# skip gunicorn tests as we dont carry package
k="${k-}${k+ and }not test_no_warnings[aiohttp.worker]"

%{__python} -m pytest -Wdefault ${ignore-} -k "${k-}" -rs --import-mode=importlib tests/
%endif

%files
%doc CHANGES.rst docs/contributing.rst CONTRIBUTORS.txt README.rst
%license LICENSE.txt
%{python_sitearch}/%{module}-%{version}.dist-info/
%{python_sitearch}/%{module}/
