%global srcname aiohttp

Name:		python-%{srcname}
Version:	3.8.1
Release:	1
Summary:	Python HTTP client/server for asyncio
License:	ASL 2.0
URL:		https://github.com/aio-libs/aiohttp
Source0:	https://files.pythonhosted.org/packages/5a/86/5f63de7a202550269a617a5d57859a2961f3396ecd1739a70b92224766bc/aiohttp-%{version}.tar.gz
BuildRequires:	pkgconfig(python)
BuildRequires:	python-setuptools
BuildRequires:	python-cython

%description
Python HTTP client/server for asyncio which supports both the client and the
server side of the HTTP protocol, client and server websocket, and webservers
with middlewares and pluggable routing.

%prep
%autosetup -p 1 -n %{srcname}-%{version}
# Remove files generated by Cython to regenerate them
	
	
 
%build
cython -3 aiohttp/*.pyx -I aiohttp
%py_build

%install
%py_install

%files
%doc CHANGES.rst docs/contributing.rst CONTRIBUTORS.txt README.rst
%license LICENSE.txt
%{python_sitearch}/%{srcname}-*.egg-info/
%{python_sitearch}/%{srcname}/
